tags:
  discounts-green: false
  products-green: false
  discountsNetworkingOffline: false
  productsNetworkingOffline: false

discountsNetworkingOnline:
  router:
    enabled: false

productsNetworkingOnline:
  router:
    enabled: false

global:
  istio:
    enabled: true
    rollouts:
      enabled: true
  namespace: test
  #TODO fixme prometheus pass
  prometheusAddress: http://prometheus-backdoor.istio-system.svc.cluster.local:9090

discounts-blue:
  mode: online
  quarkus-base:
    fullnameOverride: "discounts"
    image:
      tag: v1.0.1
    version: none
    rollouts:
      enabled: true
      analysis:
        prometheus: true
        query: sum(irate(
            istio_requests_total{reporter="source",destination_service_name=~"discounts-umbrella-online",response_code!~"5.*"}[30s]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service_name=~"discounts-umbrella-online"}[30s]
          ))
      canary:
        trafficRouting:
          istio:
            virtualService:
              routes:
              - primary
              name: shop-umbrella-vs-discounts
            destinationRule:
              name: shop-umbrella-discounts-rule
              canarySubsetName: canary
              stableSubsetName: stable

  fullnameOverride: "discounts"
    
products-blue:
  mode: online
  quarkus-base:
    image:
      tag: v1.1.1
    version: none
    replicaCount: 4
    fullnameOverride: "products"
    rollouts:
      enabled: true
      analysis:
        prometheus: true
        query: sum(irate(
            istio_requests_total{reporter="source",destination_service_name=~"products-umbrella-online",response_code!~"5.*"}[30s]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service_name=~"products-umbrella-online"}[30s]
          ))
      canary:
        trafficRouting:
          istio:
            virtualService:
              routes:
              - primary
              name: shop-umbrella-vs-products
            destinationRule:
              name: shop-umbrella-products-rule
              canarySubsetName: canary
              stableSubsetName: stable
        steps:
          - setWeight: 10
          - pause:
              duration: 30s
          - setWeight: 50
          - pause:
              duration: 30s
  fullnameOverride: "products"

fullnameOverride: "shop-umbrella" 








