discountsNetworkingOnline:
  version: blue
discountsNetworkingOffline:
  version: green

productsNetworkingOnline:
  version: green
  router:
    enabled: true
productsNetworkingOffline:
  version: blue
  router:
    enabled: true

products-green:
  quarkus-base:
    replicaCount: 2
    image:
      tag: v1.1.1
  mode: online
products-blue:
  quarkus-base:
    replicaCount: 1
    image:
      tag: v1.1.1
  mode: offline

discounts-green:
  quarkus-base:
    replicaCount: 1
    image:
      tag: v1.0.1
  mode: offline
discounts-blue:
  quarkus-base:
    replicaCount: 2
    image:
      tag: v1.0.1
  mode: online

