{{ if .Values.router.enabled  }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "networking.labels" . | nindent 4 }}
  name: {{ include "networking.fullname" . }}-route
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "networking.fullname" . }}-stable-service
    weight: 100
  alternateBackends:
    - kind: Service
      name: {{ include "networking.fullname" . }}-canary-service 
      weight: 0
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{ end }}
