apiVersion: v1
kind: Service
metadata:
  name: {{ include "networking.fullname" . }}-stable-service
  labels:
    {{- include "networking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "networking.selectorLabels" . | nindent 4 }}
    {{- with .Values.version }}
    version: {{ . }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "networking.fullname" . }}-canary-service
  labels:
    {{- include "networking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "networking.selectorLabels" . | nindent 4 }}
    {{- with .Values.version }}
    version: {{ . }}
    {{- end }}
